name: CI/CD Pipeline for Flask

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  deploy:
    runs-on: [self-hosted, windows]  # Use your self-hosted runner on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Python is installed
        shell: powershell
        run: |
          # Check if Python is installed and display its version
          python --version
          if (-not $?) {
              Write-Error "Python is not installed or not in PATH"
              exit 1
          }

      - name: Install dependencies
        shell: powershell
        run: |
          # Upgrade pip and install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to School Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          PROJECT_DIR: "/home/${{ secrets.SERVER_USER }}/public_html"
        shell: powershell
        run: |
          # Save SSH private key to a file
          echo "$env:SSH_PRIVATE_KEY" > private_key.pem
          # Set proper permissions for the key
          icacls private_key.pem /grant Everyone:F
          # Transfer files to the server using SCP
          scp -i private_key.pem -r . "$env:SERVER_USER@$env:SERVER_IP:$env:PROJECT_DIR"
          # Clean up by removing the private key file
          Remove-Item -Force private_key.pem
