name: CI/CD Pipeline for Flask

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to School Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          PROJECT_DIR: "/home/${{ secrets.SERVER_USER }}/public_html"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Transfer all files
          scp -i private_key.pem -r . $SERVER_USER@$SERVER_IP:$PROJECT_DIR

          # Restart Flask app (Modify based on your server setup)
          ssh -i private_key.pem $SERVER_USER@$SERVER_IP << 'EOF'
          cd $PROJECT_DIR
          pkill -f "flask run" || true  # Stop existing Flask app
          nohup flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          EOF

          rm -f private_key.pem