name: CI/CD Pipeline for Flask

on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to School Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          PROJECT_DIR: "/home/${{ secrets.SERVER_USER }}/public_html"
        run: |
          # Store SSH private key in a file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Transfer all files to the server
          scp -i private_key.pem -r . $SERVER_USER@$SERVER_IP:$PROJECT_DIR

          # Clean up the SSH private key file
          rm -f private_key.pem
