name: CI/CD Pipeline for Flask
on:
  push:
    branches:
      - main  # Change this to match your main branch

jobs:
  deploy:
    runs-on: Linux  # Change to Linux runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Python Installation
        run: |
          python3 --version
          python3 -m pip --version

      - name: Install dependencies in Virtual Environment
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip
          venv/bin/pip install -r requirements.txt

      - name: Deploy to School Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          PROJECT_DIR: "/home/${{ secrets.SERVER_USER }}/public_html"  # Adjust path for Linux
        run: |
          # Save SSH private key
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Deploy using rsync over SSH
          rsync -avz --delete -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" . $SERVER_USER@$SERVER_IP:$PROJECT_DIR

          # Restart Flask app
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            cd $PROJECT_DIR
            pkill -f 'flask run' || true
            nohup venv/bin/python -m flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          EOF

          # Clean up the private key file
          rm -f private_key.pem
